services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: paywalls
      POSTGRES_USER: paywalls
      POSTGRES_PASSWORD: paywalls
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
