# Generated by Django 4.2.11 on 2024-07-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paywalls', '0002_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paywall',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
