# Generated by Django 4.2.11 on 2024-07-25 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paywalls', '0005_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paywall',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paywall',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paywall',
            name='last_modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='paywall',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_paywalls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paywall',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
