# Generated by Django 4.2.11 on 2024-07-23 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paywalls', '0003_paywall_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paywalls.team'),
        ),
    ]
