# Generated by Django 4.2.11 on 2024-07-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paywalls', '0004_user_current_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
