# Generated by Django 4.2.11 on 2024-07-29 20:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paywalls', '0006_paywall_created_by_paywall_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(blank=True, max_length=200, null=True)),
                ('parameters', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paywalls.team')),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp', 'team_id', 'event_name'], name='paywalls_ev_timesta_d9bb63_idx')],
            },
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS paywalls_event ON paywalls_event((parameters->>'aliasId'));",
            reverse_sql='DROP INDEX "posthog_person_email";',
        )
    ]
